spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:testpass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

# Flyway
flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: 8080
